export default [
    {
        "owned":true,
        "libName":"MxM_CountDown",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"udm"
    },
    {
        "owned":false,
        "libName":"lodash",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"node"
    },
    {
        "owned":false,
        "libName":"sdfsdf",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"sdfsdaf",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"5132f",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"asgrv23",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"lodafdsaf35sh",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"ab4b2frs",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"sdfsb143df",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"sdfsdaf",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"231gv13",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"sdafsdabfdsb",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"lodafds12.g31af35sh",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
    {
        "owned":false,
        "libName":"v31v1v1",
        "github":"",
        "npm":"",
        "cdn":"",
        "icon":"",
        "state":1,
        "env":"browser"
    },
]